### ISSUE TITLE
compiling bootstrap highly parallel leads to 'make' complaints

### ISSUE THREAD

**Issue by skalk** [kernkonzept/bootstrap#1]
In the past we sporadically observed a failed build of `bootstrap` when building it with -j8 or higher. After an update of the whole build infrastructure and bootstrap, I can now reproduce that issue when building for x86_64 quite good.
The error I repeatedly get is:
```
      [bootstrap]    [bootstrap] ... Building Dependencies
      [bootstrap]    [bootstrap] ... Building Dependencies
      [bootstrap]    [bootstrap] ... Generating bootstrap.ld
      [bootstrap]    [bootstrap] ... Compiling ARCH-amd64/crt0.o
      [bootstrap]    [bootstrap] ... Compiling exec.o
      [bootstrap]    [bootstrap] ... Compiling module.o
      [bootstrap]    [bootstrap] ... Compiling base_critical.o
      [bootstrap]    [bootstrap] ... Compiling region.o
      [bootstrap]    [bootstrap] ... Compiling startup.o
      [bootstrap]    [bootstrap] ... Compiling init_kip_f.o
      [bootstrap]    [bootstrap] ... Compiling libc_support+.o
      [bootstrap]    [bootstrap] ... Compiling koptions.o
      [bootstrap]    [bootstrap] ... Compiling platform_common.o
      [bootstrap]    [bootstrap] ... Compiling memory.o
      [bootstrap]    [bootstrap] ... Compiling boot_modules.o
      [bootstrap]    [bootstrap] ... Compiling platform/x86_pc.o
      [bootstrap]    [bootstrap] ... Compiling ARCH-x86/reboot.o
      [bootstrap]  /home/sk/src/genode/contrib/foc-26e5edb7a5b66fc2b5a1eb7b3882b22f0929bbd0/src/kernel/foc/l4/pkg/bootstrap/server/src/Make.rules:467: *** missing separator.  Stop.
      [bootstrap]  make[6]: *** Waiting for unfinished jobs....
      [bootstrap]    [bootstrap] ... Compiling boot_idt.o32
      [bootstrap]    [bootstrap] ... Compiling boot.o32
      [bootstrap]  ../../../../mk/binary.inc:149: recipe for target '/home/sk/src/genode/build/x86_64/var/libcache/syscall-foc/pc-build/pkg/bootstrap/server/src/OBJ-amd64_K8' failed
      [bootstrap]  make[5]: *** [/home/sk/src/genode/build/x86_64/var/libcache/syscall-foc/pc-build/pkg/bootstrap/server/src/OBJ-amd64_K8] Error 2
      [bootstrap]  ../../../mk/subdir.mk:41: recipe for target 'src' failed
      [bootstrap]  make[4]: *** [src] Error 2
      [bootstrap]  ../../mk/subdir.mk:41: recipe for target 'server' failed
      [bootstrap]  make[3]: *** [server] Error 2
```
I could hunt down the problem to the combination of compilation unit `ARCH-x86/mb2.S`, and the expression `$(eval $(call BID_MAKE_RULE_CREATE_SUBDIR))` in its rule. When eliminating the `eval` expression everything is fine.
I wonder whether the intention behind commit-id 61c59ecf8793fc2d3cdbbe4fe78caa854db46cc5 that brought in the `eval` expression is still correct. It seems to me that the compilation rule itself always leads to the creation of the necessary subdirectory, but to be honest, the build-system is a bit complex to easily overview what is happening.
When reverting the referenced commit, I do not have any issues regarding parallel build anymore.

**Comment by icedieler** [comment]
Thanks for bringing this up. I can reliably reproduce this in a fresh build directory. I will have to ask one of our build system experts though.

**Comment by skalk** [comment]
@icedieler thank you.

**Comment by icedieler** [comment]
Could you please have a look into commit https://github.com/kernkonzept/bootstrap/commit/36500c1253f46f527098febd4da7cbc9d0e2c218? This should fix the issue.

We are not completely sure what was wrong but it seems that at least some versions of make do not like to have an eval expression within an already expanded make rule.

**Comment by skalk** [comment]
Works like a charm. Thank you for the investigation. Commit 36500c1 solves the issue, so I'll close it again.
