### ISSUE TITLE
Problem: Undefined reference to __popcountdi2 when building platform/x86_efi_pc.cc

### ISSUE THREAD

**Issue by lbakman** [kernkonzept/bootstrap#2]
Hi

Not sure this is the right project to post this in, but I choose the bootstrap project as this is the place where the problem manifests.

I am very new to l4re and fiasco, but I am trying to build the two of them to boot with UEFI (platform/x86_efi_pc) using the instructions from [Manifest WIKI](https://github.com/kernkonzept/manifest/wiki/BUILDING). I use ham to synchronise the project from the manifest project.

The project builds fine, up to the point where I want to create either a GRUB2 ISO image or an EFI image.

The commands `make E=hello efiimage MODULE_SEARCH_PATH="${PWD}/../build-fiasco"` or `make E=hello grub2iso MODULE_SEARCH_PATH="${PWD}/../build-fiasco"` produces the following error:

```
  [bootstrap] ==> Linking bootstrap.elf
x86_64-linux-gnu-ld: platform/x86_efi_pc.o: in function `(anonymous namespace)::Platform_x86_efi::construct_mbi(unsigned long, Internal_module_list const&)':
..../l4/pkg/bootstrap/server/src/platform/x86_efi_pc.cc:131: undefined reference to `__popcountdi2'
x86_64-linux-gnu-ld: ..../l4/pkg/bootstrap/server/src/platform/x86_efi_pc.cc:133: undefined reference to `__popcountdi2'
x86_64-linux-gnu-ld: ..../l4/pkg/bootstrap/server/src/platform/x86_efi_pc.cc:135: undefined reference to `__popcountdi2'
make[3]: *** [..../l4/mk/prog.mk:144: bootstrap.elf] Error 1
make[2]: *** [../../../../mk/binary.inc:197: ..../build-l4/pkg/bootstrap/server/src/OBJ-amd64_gen-std-plain] Error 2
make[1]: *** [Makefile:607: efiimage] Error 2
make[1]: Leaving directory '..../l4'
make: *** [Makefile:6: do-all-make-goals] Error 2
```

The code in x86_efi_pc.cc references __builtin_popcount which is translated to __popcountdi2.

If I go back to commits pushed on the 16th of January this year, the above commands works fine and there is no problem building both grub2image and efiimage.

The manifest with revisions where the build works:
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote
    name="origin"
    fetch=".."
    review=".."
  />
  <default
    revision="master"
    remote="origin"
  />
  <project name="acpica" path="l4/pkg/acpica" />
  <project name="ahci-driver" path="l4/pkg/ahci-driver" />
  <project name="atkins" path="l4/pkg/atkins" revision="d68b657e8924db0c179108669690805c3bd24266"/>
  <project name="bootstrap" path="l4/pkg/bootstrap" revision="ce9d4eff9e15117055991a00d6261bc3256e7e66"/>
  <project name="cons" path="l4/pkg/cons" />
  <project name="drivers-frst" path="l4/pkg/drivers-frst" />
  <project name="gnu-efi" path="l4/pkg/gnu-efi" revision="54acac7c7c77bcc8c9268739a432d813987c7b1d"/>
  <project name="fiasco" path="fiasco" />
  <project name="hello" path="l4/pkg/hello" />
  <project name="io" path="l4/pkg/io" />
  <project name="l4_virtio-net-switch" path="l4/pkg/virtio-net-switch" />
  <project name="l4re-core" path="l4/pkg/l4re-core" revision="a01e07e2d5a92afd270f94230c254eca967e7f24"/>
  <project name="l4virtio" path="l4/pkg/l4virtio" />
  <project name="libblock-device" path="l4/pkg/libblock-device" />
  <project name="libfdt" path="l4/pkg/libfdt" />
  <project name="libvcpu" path="l4/pkg/libvcpu" />
  <project name="mk" path="l4" revision="53cc257ed92f188c681d3f1f54452143b48b22df"/>
  <project name="nvme-driver" path="l4/pkg/nvme-driver" />
  <project name="readline" path="l4/pkg/readline" />
  <project name="uvmm" path="l4/pkg/uvmm" revision="346028712f406ab4f92218582467a0a7b962f117"/>
  <project name="virtio-net" path="l4/pkg/virtio-net" />
  <project name="zlib" path="l4/pkg/zlib" />
</manifest>
```

The Dockerfile I use to build the system:
```
FROM debian:12-slim

RUN apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        build-essential \
        device-tree-compiler \
        libncurses-dev \
        g++-multilib \
        libelf-dev \
        pkg-config \ 
        dialog \
        bison \
        gawk \
        flex \
        bc \
        mtools \
        grub-efi-amd64 grub-efi-amd64-signed \
        less \
        xorriso

RUN rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
```

Unfortunately I am not in a position where I can pinpoint the problem and create a pull request. 

I hope this issue can be resolved so it is possible to build for UEFI again. 

Regards 
Lau Bakman

**Comment by phipse** [comment]
Hi Lau,

thanks for using L4Re and taking the time to write an issue. We noticed this just recently ourselves and have a fix in the making. This fix should land in the repo in one of the next releases. 
Is using the 2024-01-16 version fine for you? If not, I can check if we have a temporary workaround. 

Cheers,
Philipp

**Comment by lbakman** [comment]
Hi Philipp

Thank you for the response. 

Yes, the 2024-01-16 version is fine for now. There is plenty for me to learn already, so I am good. Just wanted to make sure you were aware of the problem.

Regards Lau

**Comment by icedieler** [comment]
Hi @lbakman ,

this issue has been fixed by [this commit](https://github.com/kernkonzept/l4re-core/commit/4a6bb4d28ececc97acc852205d46118b614dbaa2) in the `l4re-core` project. Please do a `ham sync` to update your working copy and rebuild `l4re-core`.

I'll close this issue.

Regards,
Matthias.
